db:
  image: mysql
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: olympiad
    MYSQL_PASSWORD: olympiad
    MYSQL_DATABASE: olympiad

phpfpm:
  build: ./.docker/phpfpm
  volumes:
     - "./:/var/www/html"
  links:
     - db

nginx:
  image: nginx
  ports:
    - "8080:80"
  volumes:
      - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
  volumes_from:
    - phpfpm
  links:
    - phpfpm